[[redirects]]
  # root → /pages/index.html
  from = "/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  # /post/anything → /pages/post.html
  from = "/post/*"
  to = "/pages/post.html"
  status = 200

[[redirects]]
  # /anything → /pages/anything.html
  from = "/:slug"
  to = "/pages/:slug.html"
  status = 200
